"""replace weaviate_id with vectorized_at

Revision ID: 57b7e0e959e3
Revises: d35e0586e53a
Create Date: 2026-05-27 01:08:50.881616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b7e0e959e3'
down_revision: Union[str, Sequence[str], None] = 'd35e0586e53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('vectorized_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('documents_weaviate_id_key'), 'documents', type_='unique')
    op.drop_column('documents', 'weaviate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('weaviate_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('documents_weaviate_id_key'), 'documents', ['weaviate_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'vectorized_at')
    # ### end Alembic commands ###