"""add_subject_unique_constraint

Revision ID: 5831a789d9ec
Revises: 69dad4d0577f
Create Date: 2026-04-23 20:20:37.636715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5831a789d9ec'
down_revision: Union[str, Sequence[str], None] = '69dad4d0577f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subject_semester_name', 'subjects', ['semester_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subject_semester_name', 'subjects', type_='unique')
    # ### end Alembic commands ###
