"""make_document_fks_non_nullable

Revision ID: 70abdf09f850
Revises: 7e59d7f05361
Create Date: 2026-04-23 19:54:24.179178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70abdf09f850'
down_revision: Union[str, Sequence[str], None] = '7e59d7f05361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
