"""add index on refresh_tokens token_hash

Revision ID: f8f989583499
Revises: 5831a789d9ec
Create Date: 2026-04-24 01:02:17.374245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f989583499'
down_revision: Union[str, Sequence[str], None] = '5831a789d9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    # ### end Alembic commands ###
